config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
  devise_for :users
  
  get '/articles/search' => 'articles#search', :as => 'search_articles'

  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    include Visible
    belongs_to :author, class_name: 'User'
    has_one_attached :image
    has_many :comments, dependent: :destroy
  
    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }
    validates :image, presence: true

    paginates_per 3

  end
  

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  belongs_to :article
  belongs_to :author, class_name: "User"
end

app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern
  
    VALID_STATUSES = ['public', 'private', 'archived']
  
    included do
      validates :status, inclusion: { in: VALID_STATUSES }
    end
  
    class_methods do
      def public_count
        where(status: 'public').count
      end
    end
  
    def archived?
      status == 'archived'
    end
  end
  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :rememberable :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable

  has_many :articles,foreign_key: :author_id, dependent: :destroy
  has_many :comments, foreign_key: :author_id, inverse_of: :author

  ROLES = {
    user: 0,
    admin: 1
  }.with_indifferent_access.freeze

  enum role: ROLES
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit
    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password)}
  
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :current_password)}
    end

    private
    def user_not_authorized
        flash[:alert] = "You are not authorized to perform this action."
        redirect_to(request.referrer || root_path)
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

   before_action :authenticate_user!, only: %i[ new create edit update destroy]
  
  def index
    authorize Article
    @articles = Article.order(created_at: :desc).includes(:author).page params[:page]
  end

  def show
    @article = Article.find(params[:id])
    authorize @article
  end

  def new
    @article = Article.new
    authorize Article
  end

  def create
    authorize Article
    @article = Article.new(article_params)

    @article.author = current_user

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
    authorize @article
  end

  def update
    
    @article = Article.find(params[:id])
    authorize @article

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    authorize @article
    @article.destroy

    redirect_to root_path
  end

  def search
    if params[:search].blank?
      redirect_to root_path
    else
      @parameter = params[:search].downcase
      @articles = Article.all.where("lower(body) LIKE :search OR lower(title) LIKE :search", search: "%#{@parameter}%")
    end
  end




    private
    def article_params
      params.require(:article).permit(:title, :body, :status, :image)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: %i[ create destroy]
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params.merge(:author_id => current_user.id))
    @comment.author = current_user
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    authorize @comment
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:body, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
      <% article.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
    <%= form.label :image %><br>
    <%= form.file_field :image %>
    <% article.errors.full_messages_for(:image).each do |message| %>
      <div><%= message %></div>
    <% end %>
    </div>

    <div>
      <%= form.label :body %><br>
      <%= form.text_area :body %><br>
      <% article.errors.full_messages_for(:body).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
    
    <div>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>

Our blog has <%= Article.public_count %> articles and counting!

<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article %>
    </li>
  <% end %>
</ul>

<%= link_to "New Article", new_article_path %>
<%= paginate @articles %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>
<%= link_to "Back", root_path %>

app/views/articles/search.html.erb
<h2>Search results for '<%= @parameter %>':</h2>
<div>
<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article %>
    </li>
  <% end %>
</ul>
<%= link_to "Back", root_path %>
</div>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p>
  <strong>Author:</strong>
  <%= @article.author.username%>
</p>
<p>

  <%= image_tag(@article.image, width: 475) if (@article.image.attached?)%>
</p>
<p><%= @article.body %></p>

<p>
  <% if policy(@article).update? %>
    <%= link_to "Edit", edit_article_path(@article) %> |
    <% end %>
  <% if policy(@article).destroy?%>
    <%= link_to "Destroy", article_path(@article),
                          method: :delete,
                          data: { confirm: "Are you sure?" } %>
  <% end %>
</p>


<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to "Back", root_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.author.username %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
<% if policy(@article).update? %>
<%= link_to 'Destroy Comment', [comment.article, comment],
            method: :delete,
            data: { confirm: "Are you sure?" } %>
    <% end %>
</p>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>

    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>
    <p>
  <%= form.label :status %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
</p>

  <% end %>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhosDown</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>

  <body>
.......
  <header>
    <% if user_signed_in?%>
      <%= current_user.username %> | 
      <%= link_to 'Log out', destroy_user_session_path, 
                  method: :delete, data: {confirm: 'Are you sure?'}%>
    <% else %>
      <%= link_to 'Log in', new_user_session_path%> 
    <% end%>
    <%= form_with url: search_articles_path, method: :get do %>
      <%= search_field_tag :search, params[:search], placeholder: "Search..." %>
    <% end %>
  </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>